- hosts: ansible_machine
  tasks:
    - name: Create group
      group:
        name: apache
        state: present

    - name: Create user
      user:
        name: ansible
        group: apache

    - name: Install Apache
      yum:
        name: httpd
        state: present
